const config = [10, 11]

const mySheet = [
  { group: ['a1', 'a2'], value: '[1]' },
  { group: ['a1', 'a2'], value: '[2]', show: false },
  { group: ['a3'], value: '[3]' },
  { group: ['a4'], value: '[4]' },
  { group: ['a5'], value: '[5]' },
  { group: ['a6'], value: '[6]' },
  { group: ['a7'], value: '[7]' },
  { group: ['a8'], value: '[8]' },
  { group: ['a9'], value: '[9]' },
  { group: ['a10'], value: '[10]' },
  { group: ['b11'], value: '[11]' },
  { group: ['b12'], value: '[12]' },
  { group: ['b13'], value: '[13]' },
  { group: ['b14'], value: '[14]' },
  { group: ['b15'], value: '[15]' },
  { group: ['b16'], value: '[16]' },
  { group: ['b17'], value: '[17]' },
  { group: ['b18'], value: '[18]' },
  { group: ['b19'], value: '[19]' },
  { group: ['b20'], value: '[20]' },
  { group: ['c21'], value: '[21]' },
  { group: ['c22'], value: '[22]' },
  { group: ['c23'], value: '[23]' },
  { group: ['c24'], value: '[24]' },
  { group: ['c25'], value: '[25]' },
  { group: ['c26'], value: '[26]' },
  { group: ['c27'], value: '[27]' },
  { group: ['c28'], value: '[28]' },
  { group: ['c29'], value: '[29]' },
  { group: ['c30'], value: '[30]' },
]

export default mySheet
